### ISSUE TITLE
"autoResize" is not serialized

### ISSUE THREAD

**Issue by kabong009** [HdrHistogram/HdrHistogram#103]
The field autoResize is reset to false when the histogram object is serialized. It may be because autoResize is a member of AbstractHistogramBase and since the Serializable interface is implemented a level below (in AbstractHistogram) it does not get carried over during serialization.

**Comment by giltene** [comment]
Can you provide a test case or a description of when you've seen autoResize reset to false on serialization, or where it was not serialized/deserialized correctly? I've added tests that verify that it is...

**Comment by kabong009** [comment]
First, thank you for such a great tool.
I'm seeing this behavior when using it inside an Apache Spark job written in Scala. I'll try to create a test case and verify if it's an issue with Spark using a different serializer and get back to you.

**Comment by giltene** [comment]
@kabong009, I'm closing the issue for now, as my tests seem to verify autoResize is being serialized. Please re-open if you are still seeing this and/or have a reproducer.
