### ISSUE TITLE
Min and max not same for a single sample

### ISSUE THREAD

**Issue by belousa** [HdrHistogram/HdrHistogram#105]
This is not exactly a bug report - rather it's a question.

The code of `getMinNonZeroValue` is now deliberately written so that the test below fails. Could someone explain why?

```
    @Test
    public void testHistogram() throws Exception {
        Histogram stats = new Histogram(2);

        stats.recordValue(35071);
        assertEquals(1, stats.getTotalCount());
        assertEquals(35071, stats.getMaxValue());
        assertEquals(35071, stats.getMinNonZeroValue());
    } 
```

**Comment by mikeb01** [comment]
I'm not sure that this has changed recently, but with a `new Histogram(2)`, the histogram is configured to given at least a 2 significant figure accuracy.  When the value `35071` is recorded in the histogram, the exact value is not stored.  Instead a counter is incremented to indicate that there is an additional value in the range of 34816 to 35071, so the information about the exact value is lost.  Therefore the `minNonZeroValue` value is the low end of the lowest valued range with a non-zero count and inversely the`maxValue` is the high of the highest value range with a non-zero count.

**Comment by giltene** [comment]
@mikeb01 explanation above is correct. The proper test would look like this:

`    @Test
    public void testHistogram() throws Exception {
        Histogram stats = new Histogram(2);

        stats.recordValue(35071);
        assertEquals(1, stats.getTotalCount());
        assertTrue(stats.valuesAreEquivalent(35071, stats.getMaxValue()));
        assertTrue(stats.valuesAreEquivalent(35071, stats.getMinNonZeroValue()));
    }
`
And that test passes.

**Comment by belousa** [comment]
I guess I needed to be more precise when I said "deliberately written". We *do* have the precise value of minimum, and then we go out of our way to *convert* it to the bottom of the bucket.

Now that I had some time to think about it, I realize that one reason may be to make sure that minimum matches the results of iteration over buckets.

If that is indeed the reason, would it be useful to add a getter for "true" minimum? We do have that number available.

**Comment by giltene** [comment]
This took some thought and work earlier in HdrHistogram's life. The bottom line is that treating any percentile or value level in some special way to provide precision (just for that level) that is better than the histograms underlying precision for similar/nearby values creates logical inconsistencies for API users, and "surprising" results that are harder to explain than "this falls within precision". E.g. The 99.999%'ile can end up being higher than the Max. Or the 0.00000001%'ile can be lower than the min. Yes, each of those corners could then be duct-taped over with code that special-handles against max and min, but there are many such corners, and the special handling screams "This is architecturally wrong. And buggy".

The current logic is mathematically consistent. The min will always be <= than all values recorded into or returned from a histogram, and the max will always be >= than all values recorded into or returned from s histogram. getValueAtPercentile() returns the highest equivalent value for that percentile for all percentiles other than 0.0 (for which it returns the lowest equivalent value to match min).

So min (and the 0.0 percentile) are the only ones with "special handling", and that special handling is there to avoid returning a min value that is higher than an actual recorded value or some other possible value one may get from querying the histogram...

**Comment by belousa** [comment]
Thank you very much, this is exactly the explanation I needed.
