### ISSUE TITLE
Rust port

### ISSUE THREAD

**Issue by jonhoo** [HdrHistogram/HdrHistogram#107]
@giltene: As you saw on Twitter, I've written a [Rust port](https://github.com/jonhoo/hdrsample) of HdrHistogram. It is about on feature parity with the Python port at the moment as far as I can tell. I'm also planning on porting more features as I get the time (which [ones](https://github.com/jonhoo/hdrsample#limitations-and-caveats) do you think I should prioritize?). Would you consider adding it to the official list of ports?

On a separate note, I've licensed the code under MIT/Apache 2.0, which is the de facto Rust license. Hope that's okay? I also refer back to HdrHistogram where appropriate, but am happy add more attribution if you feel like it's a bit on the light side at the moment :)

**Comment by giltene** [comment]
What's the status of the Rust port? Is it ready to be moved under the HdrHistogram org?

**Comment by jonhoo** [comment]
I've been using it for a few personal projects, the ported test suite still passes, and I've added a few more features, so yes, I'd say so. It's at least as feature complete as many of the other listed ports.

**Comment by giltene** [comment]
I believe @marshallpierce also has a Rust port at https://github.com/ogeagla/HdrHistogram_Rust . This seems to be a common thing (we've had multiple .NET and multiple Python port as well). It would be good for the two of you to compare notes and maybe work together on what a HdrHistogram/HdrHistogram_Rust would/should look like. I'm happy to have either (or both) of you own that repo. 
One feature that is very important to have in each implementation (and that AFAICT both implementations currently lack) is a histogram log writer. Decoding and log reading is not as critical (since there are other tools that will read logs), but being able to output to the commonly used format will allow log analyzers and visualizers (and even time series DBs) to use data recorded from the Rust implementations.

**Comment by marshallpierce** [comment]
I'd be happy to collaborate/merge/whatever. I wrote the Rust one almost all myself and perhaps there are better ways of doing things than the ways I chose. Work got busy with other things, etc, so I haven't made progress in several months. 

I have a branch with some progress on a log writer (zig zag encoding and stuff), but definitely not complete.

**Comment by jonhoo** [comment]
Hey, sorry I've been slow to follow up, working on a couple of things concurrently that are keeping me pretty busy.

I'd be happy to look at bringing @marshallpierce's implementation (who is @ogeagla?)  and mine together somehow. When implementing my port, I copied the HdrHistogram Java code and ported it nearly line-by-line, so it shouldn't be too hard to read familiarize yourself with the code if you already know the Java code. There are some type parameters there to make it generic over the measurement type (`u8`, `u16`, `u32`, `u64`, `i8`, etc.), some implementation of common Rust traits (like `AddAssign`) to make the library more idiomatic to use, and iterators follow a slightly different pattern to HdrHistogram, but apart from that they should be similar.

From a *very* cursory look, mine seems more complete, both feature-wise and in terms of external documentation, but I could be wrong. The test suites should probably be merged (@marshallpierce, are your tests generally copied from HdrHistogram, or are they self-written?). His (?) does have better internal comments that may be a good addition to mine, and seems to also support normalization, which mine does not. Neither of us have log writing, though I don't think it should be too tricky to add to either.

I'd obviously prefer to start with my codebase (I'd be happy to give @marshallpierce commit access), but I'm not tied to that. Thoughts from either of you?

**Comment by marshallpierce** [comment]
@jonhoo I started the project with @ogeagla at a conference last year as a "let's learn Rust on something real" project, and then continued hacking on it afterwards.

I didn't go line-by-line; I wrote it starting at the lowest level functionality, making sure I understood it, and working up, testing as I went (and adding docs to the Java project as I learned how it worked). So, the tests are not colored by how the Java version is written but rather based on my understanding of corner cases, and should be valuable as at least a cross-check. I wrote the code carefully, but it was my first real-ish Rust project, so while I may have made dumb mistakes, I did at least test it thoroughly. :)

I'm not tied to starting with my codebase, especially as I have little time (though still non-zero, at least for now) to give to this effort. If you can make use of only my tests and comments, I'll be glad something useful came out of my spare-time project. :) Rust is going to be part of my day-to-day development soon, and I want a good HdrHistogram implementation available, whether it has my commits in its history or not.

**Comment by jonhoo** [comment]
Ah, I see, so we approached it from fairly different angles. I think adding in your tests could be very valuable then! Given your then presumably deep understanding of how the original HdrHistogram works, it should be trivial for you to familiarize yourself with the code in my port ([`hdrsample`](https://github.com/jonhoo/hdrsample) if you haven't seen it already). I'm also pretty strapped for time, at least for the coming week or two, so probably won't be able to help doing substantial work until things calm down.

A good path forward would probably be to first fold your tests into the test suite for `hdrsample` (probably as a new file in [`tests/`](https://github.com/jonhoo/hdrsample/tree/master/tests); the existing tests should serve well as usage examples). In theory they should all pass, but we both know that tests never do the first time around. After that, we should probably move over your normalization implementation, as I think that's the biggest feature yours has that mine doesn't. Given that those are "yours", I think you should be the one to commit those (if you want to). As I said, I'd be happy to give you commit access to the `hdrsample` repository. If we do this, we should also add a link back to your original implementation for attribution :) 

As a side note, congrats on landing a job where Rust can be in your day-to-day development! Sounds exciting. Rust is a fun language to work with.

**Comment by marshallpierce** [comment]
I'll dive back into the code over the coming days/weeks and let you know as I have questions, etc. I usually have a couple hours a week to dedicate to OSS stuff. To stop treating this issue like a chat room, should we move to the gitter room for hdrhistogram? Or maybe something else, as there's likely to be mostly rust-specific discussion?

**Comment by jonhoo** [comment]
Sounds good! E-mail is probably fine. I'm jon at thesquareplanet dot com.

**Comment by ogeagla** [comment]
Yea I'm happy to dive back in and work on this also!

**Comment by yxhuvud** [comment]
@giltene Regarding log writer and readers, is the output formats documented somewhere or is the only way to understand them to read the other implementations? I'm asking as I'm writing a (Crystal)[https://github.com/yxhuvud/hdrhistogram] implementation and the persistance layer have been quite confusing so far.

**Comment by giltene** [comment]
You find some fairly good documentation of the common histogram encoding and the log format here: 
https://github.com/HdrHistogram/HdrHistogram.NET/wiki/Encoded-Histogram-format
and
https://github.com/HdrHistogram/HdrHistogram.NET/wiki/V2-Log-Encoding

And yes, we should really add this in a language-neutral place...
