### ISSUE TITLE
no function to decode ConcurrentDoubleHistogram

### ISSUE THREAD

**Issue by andrewzhaosc** [HdrHistogram/HdrHistogram#110]
ConcurrentDoubleHistogram does not have an overload for decodeFromByteBuffer and also doesn't have any way to cast down from a DoubleHistogram.

**Comment by giltene** [comment]
While there is no way to directly decode into a ConcurrentDoubleHistogram, you can decode into a DoubleHistogram and use copyInto to populate a newly constructed (or cleared) ConcurrentDoubleHistogram.
