### ISSUE TITLE
Build fails with Java 9

### ISSUE THREAD

**Issue by FauxFaux** [HdrHistogram/HdrHistogram#125]
In Java 9, the `javax.xml.bind` package is gone by default, which causes a lot of the tests to fail. Java 9 is due out in ten days.

There's some discussion on the Debian wiki about workarounds for this, but the situation is pretty grim:
https://wiki.debian.org/Java/Java9Pitfalls (under "javax.xml.bind").

Can the tests be fixed to use a different XML API that supports Java 9, or do you have any suggestions on how I can run the tests on Java 9?

**Comment by giltene** [comment]
Fixed with https://github.com/HdrHistogram/HdrHistogram/commit/c410c5c2699b69ce0eb026ff954fefc4045ec363 and https://github.com/HdrHistogram/HdrHistogram/commit/296902df060cbdc1d689f63f8dec3e5fe4bf7ee0 . Now builds and runs all tests succesfully with Java 6...9.

**Comment by giltene** [comment]
Also, just released HdrHistogram 2.1.10 to maven and posted to maven central. Works on Java 6...9
