### ISSUE TITLE
Recorder's default  value level

### ISSUE THREAD

**Issue by ArvinDevel** [HdrHistogram/HdrHistogram#129]
Is the value recorded by recorder in the microseconds level by default? 
this means that after I declared ` Recorder recorder = new Recorder(TimeUnit.SECONDS.toMillis(120000), 5);`, I should pass value like this ` long sendTime = System.nanoTime();...
 long latencyMicros = NANOSECONDS.toMicros(System.nanoTime() - sendTime); recorder.recordValue(latencyMicros);`
If I want to change the recorded value's time level(milliseconds for example), how can I set?
Thanks.

**Comment by giltene** [comment]
Recorders HdrHistograms don't really have units. They are just a histogram of values. Could be Nanoseconds, picoseconds, years, Intensity, Watts, Ergs, Miles per second, whatever. As long you consistently use the same units when recording values (using e.g. recordValue()), and when extracting them (e.g. when using getValueAtPercentile()), you should be fine. And if you mess the units up, the obvious will happen. Some of the convenience output methods (e.g. like outputPercentileDistribution()) provide for a scaling factor (see JavaDoc http://hdrhistogram.org for explanation).

When recording latency, I usually use nanosecond units. And when summarizing histogram percentiles I usually use a scaling factor of 1,000,000 so the summary output is in millisecond units. Some percentile plotting tools (like e.g. http://hdrhistogram.github.io/HdrHistogram/plotFiles.html) default to that unit for the chart labels (but are configurable).

When using common plotting tools that take histogram logs as input and display latency units (e.g.  https://github.com/HdrHistogram/HistogramLogAnalyzer or https://hdrhistogram.github.io/HdrHistogramJSDemo/logparser.html) the common expectation seems to be that latency is recorded in nanosecond units.

**Comment by ArvinDevel** [comment]
thank you very much
