### ISSUE TITLE
Doc inconsistency? Can the SingleWriterRecorder histogram be flipped or not?

### ISSUE THREAD

**Issue by ejsarge** [HdrHistogram/HdrHistogram#131]
The JavaDoc for SingleWriterRecorder.getIntervalHistogram says

>  *NOTE: The caller is responsible for not recycling the same returned interval histogram more than once. If
>  * the same interval histogram instance is recycled more than once, behavior is undefined.

However, unless I'm misunderstanding, the [HiccupMeter](https://github.com/giltene/jHiccup/blob/5c0b2954c41c7fe5943a05a29c6c24c7465ec054/src/main/java/org/jhiccup/HiccupMeter.java ) code in jHiccup that uses it simply reuses and flips two IntervalHistogram. (Line 688).

So, what is supposed to happen? Is the caller supposed to throw away the histogram after a single recycle or to keep flipping?

**Comment by giltene** [comment]
The thing that you should not recycle twice is the return value, not neccesarily the histogram instance it represents. You can recycle a histogram instance once for each time that instance is returned from a call to getIntervalHistogram() call. Recycling the same returned value again will cause undefined behavior (including the very real possibility of corrupted or love-changing histograms). This is different from the valid recycling of another return value that you get from a subsequent call to getIntervalHistogram(), which happens to be an instance of a histogram that was previously recycled. This latter recycling behavior is fine, likely, and commonly seen in typical uses of a Recorder, e.g. cycling back and forth with two histogram instances with: one is used for the currently active recording of values, and one (the kat st one returned by getIntervalHistogram()) is stable and unchanging until it is recycled. This sort of scheme is common for e.g. repeated logging of histogram intervals without allocating any new histogram instances (the most common  use case of Recorder). The scheme is not limited to two histogram instances. E.g. systems that like to keep a moving window of the last 10 intervals will cycle through 11 histogram instances, recycling the return value received 10 calls ago in each getIntervalHistogram() call.

**Comment by ejsarge** [comment]
Thanks for the reply.

So, if I understand you then a histogram needs to go through getIntervalHistogram() before it can be recycled again.

In other words:
Bad:
`interval1 = swr.getIntervalHistogram(null);
  interval2 = swr.getIntervalHistogram(interval1);
  interval3 = swr.getIntervalHistogram(interval1);`

Good:
`interval1 = swr.getIntervalHistogram(null);
 interval2 = swr.getIntervalHistogram(interval1);
 interval3 = swr.getIntervalHistogram(interval2);`

Also good:
`interval1 = null;
  // repeat the next as often as required - because it keeps recycling the interval
  interval1 = swr.getIntervalHistogram(interval1);`

**Comment by giltene** [comment]
Right.

I updated the JavaDoc for the various recorders with an example of the common use pattern (e.g. http://hdrhistogram.github.io/HdrHistogram/JavaDoc/org/HdrHistogram/SingleWriterRecorder.html)
