### ISSUE TITLE
Feature request - top N collection alongside the histogram

### ISSUE THREAD

**Issue by mrbald** [HdrHistogram/HdrHistogram#141]
Would be nice to have a feature out-of-the-box to maintain a top N worst outliers per collected histogram (and collect/recycle/merge them the same way as it is done with the  histograms).

The API `recorder.recordValue(value, outlierDetailsSupplier)` would lazily request the outlier details from the   `outlierDetailsSupplier` if the value would be on the top N list. When two histograms are merged, the respective outliers lists are merged too.

**Comment by giltene** [comment]
I may be missing something: HdrHistorams already inherently keep track on the top N (for any N up to the total number of value recorded) "outliers". E.g. you use something roughly like this pseudo-code:

        RecordedValuesIterator recordedValuesIterator = new RecordedValuesIterator(histogram);
        long countToN = (histogram.getTotalCount() > N) ? histogram.getTotalCount() - N : 0;
        for (HistogramIterationValue v : histogram.recordedValues()) {
            if (v.getTotalCountToThisValue() > countAtN) {
                 System.out.println("Outlier value " + v.getValueIteratedTo() + " appeared " +
                                                      v.countAtValueIteratedTo() + " times");
            }
        }

**Comment by giltene** [comment]
We could add a highToLowRecordedValuesIterator for efficiency. But that seems like a bit much for this use case...

**Comment by mrbald** [comment]
This is to store additional info for the extreme outliers _in addition to the samples value_, a query correlation ID, an exact timestamp, etc. to support the root cause analysis.

**Comment by vladimir-bukhtoyarov** [comment]
@mrbald it looks like you need in something like this https://github.com/vladimir-bukhtoyarov/rolling-metrics/blob/master/top.md

**Comment by giltene** [comment]
This seems to be something you can build by subclassing Histogram and SingleWriterRecorder (or ConcurrentHistogram and Recorder, if you want to deal with concurrency), maintaining a top-list and associated apis in your subclasses, and overriding the recording methods (as well as add/subtract/etc) to do so. If you evolve an interesting-enough subclass set that you think can/should be added to the library, I’d be happy to look at it for inclusion.

Closing issue for now.
