### ISSUE TITLE
SynchronizedHistogram.getTotalCount does not guarantee visibility of totalCount

### ISSUE THREAD

**Issue by shayshim** [HdrHistogram/HdrHistogram#146]
Hello,
As I understand from the documentation, SynchronizedHistogram is supposed to be thread safe for queries, like getTotalCount, but in fact I don't see any synchronization for the totalCount variable (like volatile or synchronized), so querying thread might see constantly out-of-date value, while recording thread keeps updating it. Or maybe I miss something.
Same is true for getValueAtPercentile (and others), which relies on getTotalCount. In that method totalCount is not synchronized, but later some of the calculations are synchronized, so countAtPercentile might be out of date, but totalToCurrentIndex will be up-to-date. 
Thanks,
Shay

**Comment by giltene** [comment]
There is no need to make any of the internal variables volatile. The modification and query methods are all synchronized, which prevents any modification *during* any query, and ensures that queries reflect a consistent internal state. If a querying thread is looking to prevent external modifications *between* two separate calls, it can synchronize on the histogram instance, or coordinate its multiple calls across threads in some other way.

**Comment by shayshim** [comment]
Sorry, my bad, I looked at an older version (2.1.4), so this issue is not relevant.

**Comment by giltene** [comment]
Yeah, as the internal details got more intricate with shifts, autosizing, etc., we shifted synchronization to happen systemically on all public API calls, such that internal synchronization would no longer be a concern.
