### ISSUE TITLE
Histogram getValueAtPercentile throws ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by CodingFabian** [HdrHistogram/HdrHistogram#147]
```
java.lang.ArrayIndexOutOfBoundsException: 131072
	at org.HdrHistogram.Histogram.getCountAtIndex(Histogram.java:52) ~[?:?]
	at org.HdrHistogram.AbstractHistogram.getValueAtPercentile(AbstractHistogram.java:1337) ~[?:?]
```

That histogram is set up like this:
```
      histogram = new Histogram(TimeUnit.MINUTES.toMillis(30), 4);
      histogram.setAutoResize(true);
```

there are an unknown number of calls to reset and update inbetween
```
      histogram.reset();
```
```
     histogram.recordValueWithCount(value, samplingMultiplier);
```

interestingly this exception is logged immediately after
```
histogram.getMean();
```
was invoked successfully.

it crashed on
```
histogram.getValueAtPercentile(50.0d)
```

I am trying to get a heap dump to inspect this better. Any ideas welcome. Currently I feel that the autoResize could be the problem.

Version is 2.1.10

**Comment by giltene** [comment]
Is there concurrent access involved? I.e. is the exception-throwing call to histogram.getValueAtPercentile() done on a thread that is potentially different from the one(s) performing the recordValueWithCount() and reset() calls?

**Comment by CodingFabian** [comment]
@giltene I doublechecked, but all code pathes using the histogram are synchonized on the histogram instance.

**Comment by CodingFabian** [comment]
Well, because I assumed I got this right...
 Indeed the lambda instance that is locked in one path and the real holder object in the other.
That was super unexpected and is quite likey the root cause.
Will close the issue here. Thanks Gil.

**Comment by giltene** [comment]
NP.
Out of curiosity. what is your use case for needing 4 decimal points of precision? I tend to use 2 in most cases (generally good enough for anything that gets plotted as graphics), and 3 "when I really need it". Nothing wrong with 4, or even 5, but it does take up tons more space than 2 (as in two order of magnitude)... I like to hear about what people do with this stuff and when they feel a need for such precision.

**Comment by CodingFabian** [comment]
its probably not needed.
