### ISSUE TITLE
.NET port (work in progress)

### ISSUE THREAD

**Issue by mattwarren** [HdrHistogram/HdrHistogram#15]
@giltene  (sorry I don't know a better way to contact you)

Just to let you know I'm working on a .NET port of HdrHistogram, you can see the current progress here https://github.com/mattwarren/HdrHistogram.NET.

At the moment it's has all the functionality that was in HdrHistorgram before you added HistogramLogProcessor (I plan to add that when I get time).

Hope the license and attribution is okay with you? If you'd rather host it within the main HdrHistorgram code base let me know?

BTW I plan to port jHiccup next (or at least the parts of it you can do in .NET, there isn't an Agent API like Java)

Cheers

Matt

**Comment by vitar** [comment]
While this topic marked as work in progress, I'll post here.
In AbstractHistogram.cs incorrect exception message:
"numberOfSignificantValueDigits must be between 0 and 6"
should be
"numberOfSignificantValueDigits must be between 0 and 5"

Thanks for a project!

**Comment by LeeCampbell** [comment]
This work has been moved to https://github.com/HdrHistogram/HdrHistogram. I think this can be closed now.
