### ISSUE TITLE
getPercentileAtValue() ? 

### ISSUE THREAD

**Issue by dt-rush** [HdrHistogram/HdrHistogram#150]
Is there a more efficient way and/or a way to get a more exact answer to "*what percent of values were below x?*" than the following:

(JS version used as example, but it's readable by anybody)
```node
const x = 300;
let sum = 0;
hist.recordedValuesIterator.reset();
while (hist.recordedValuesIterator.hasNext()) {
	let here = hist.recordedValuesIterator.next();
	if (here.valueIteratedTo >= x) {
		break;
	} else {
		sum += here.countAtValueIteratedTo;
	}
}
const p = sum / hist.getTotalCount();
```

The utility of answering such a question is that it allows one to produce a conventional histogram (just buckets with counts / proportions in each bucket) with *custom bucket endpoints* given an `HdrHistogram`.

**Comment by dt-rush** [comment]
Basically, we can currently get the *inverse* CDF, `getValueAtPercentile :: percentile -> value`, but we don't have a simple API access to the CDF, `getPercentileAtValue :: value -> percentile`.

The above code is capable of quite some error depending on the counts in the bins and the endpoints of the bins. It could be off by as much as the entire count of the bin for which `valueIteratedTo >= x`.

A more accurate implementation uses a binary search on the percentile-space:

```
// binary search through percentile-space [0, 100] until the error of 
// `hist.valueAtPercentile(p)` is less than `epsilonV` or percentile precision 
// is less than `epsilonP`
const estimateCDF = (
	hist: hdr.AbstractHistogram, 
	x: number, 
	epsilonV: number, 
	epsilonP: number
) => {
	let p = 50;
	let precision = 50;
	let valueAt = (p) => hist.getValueAtPercentile(p);
	let error = (p) => Math.abs(hist.getValueAtPercentile(p) - x);
	while (error(p) > epsilonV && precision > epsilonP) {
		precision /= 2;
		p += (valueAt(p) < x) ? precision : -precision;
	}
	return p;
}
```

This really has no pathological run-time so long as you don't provide `epsilonP = 0.0000000001` or something, so why not include it as a method of `AbstractHistogram` instead of having to graft it on, as I've done here?

**Comment by dt-rush** [comment]
Given that the above is still capable of quite some error in most cases, I settled for my use-case on simply using a [`t-digest`](https://github.com/welch/tdigest) to accumulate percentiles and a simple static-bin histogram implementation (insertion time is O(number of bins)) which can be made cumulative and then normalized to yield the CDF.

**Comment by giltene** [comment]
This part of the math seems wrong to me:
`sum += here.valueIteratedTo * here.countAtValueIteratedTo;
`
It should only be:
`sum += here.countAtValueIteratedTo;
`
At least in the Java iterator form, the simplest way to do this is:

```
for (HistogramIterationValue v : otherHistogram.recordedValues()) {
	if v.getValueIteratedTo() >= targetValue) {
		return v.getPercentileLevelIteratedTo();
        }
}
```

Or the more efficient (reuses bthe iteartor, rather than allocate a new one for each run):

```
hist.recordedValuesIterator.reset();
while (hist.recordedValuesIterator.hasNext()) {
	HistogramIterationValue v = hist.recordedValuesIterator.next();
	if (v.getValueIteratedTo() >= targetValue) {
		return v.getPercentileLevelIteratedTo();
        }
}
```
And yes, it does mean that you will iterate through all the sub-buckets each time.

As you note above, the actual percentile of a given value may not be precisely reconstructed, but you can determine the range the percentile fall within with:

```
for (HistogramIterationValue v : otherHistogram.recordedValues()) {
	if v.getValueIteratedTo() >= targetValue) {
                lowestPossiblePercentile = v.getPercentileLevelIteratedFrom();
                highestPossiblePercentile = v.getPercentileLevelIteratedTo();
                break;
        }
}
```
