### ISSUE TITLE
Same Numbers Showing From getValueAtPercentile() after using reset()

### ISSUE THREAD

**Issue by AlejandroHernandez996** [HdrHistogram/HdrHistogram#152]
Hello, I am an intern and was tasked to implement HdrHistogram into our projects to replace an older performance tracker. Everything has been working as expected, except that the logs keep showing the same numbers in the logs. The thing is that the programs running have millions of messages daily. It records the difference of time that a piece of code took with System.Nano, and every minute the Histogram object is reset.

This is the 99th percentile being logged with the Histogram being emptied every minute.
<img width="1232" alt="screen shot 2018-12-05 at 4 09 39 pm" src="https://user-images.githubusercontent.com/30333514/49547429-432cbe00-f8a8-11e8-9543-6797cb2fc018.png">

**Comment by giltene** [comment]
You'd have to provide more information... What is the histogram configuration (how is it constructed, with what settings)? What do the counts in the histogram look like at the points in time you show above, etc.

The quantization above (4K-1, 8K-1, 16K-1) would be "very unnatural" for a HdrHistogram, and would only occur naturally if the Histogram is configured with a 0 for numberOfSignificantValueDigits (which sort of defeats the purpose of HdrHistogram). This makes me suspect the basic configuration first...

**Comment by AlejandroHernandez996** [comment]
Sorry for the late reply. Yes that was it thank you very much!

**Comment by giltene** [comment]
I usually use 2 decimal point accuracy (numberOfSignifucantBalueDigits set to 2). It provides dynamic resolution that is within 1% for any recorded value, which is plenty fir any graphic representation, and requires much less space than 3 digits would...
