### ISSUE TITLE
Recorder for ints and shorts

### ISSUE THREAD

**Issue by luciferous** [HdrHistogram/HdrHistogram#154]
Recorder only works with Histogram (long counts). I would find it useful to be able to construct a Recorder that could be backed by Histrogram, IntCountsHistogram or ShortCountsHistogram. Then the component that records values can just use the Recorder without knowledge of the specific type of histogram that is backing it.

I could take a stab at this with some design advice.

**Comment by giltene** [comment]
I've been working on a PackedHistogram variant, which would (for the vast vast vast majority of uses) use less storage than a ShotHistigram but can support long counts. It would be somewhat slower in typical recording speed, and involve resizing reallocations under the hood as the number of values (not counts) covered by the packed backing store array changes.

Would something like that (with a corresponding PackedRecorder) meet your needs?

**Comment by luciferous** [comment]
Slowing down typical recording speed might not work for me. I was looking to choose a backing array type dependent on the highest trackable value.

**Comment by giltene** [comment]
For existing Histograms, the type (short, int, long) is for the count, not the value.

It is the highest trackable count that determines the type (short, int, long). When the count for any single value recorded overflows the maximum value of that type, the histogram will no longer be correct (actually it is an overflow of the count for an equivalent value range which is the value +/- precision). So the type determines the cap on how many times you can safely record values in the histogram.

Values are always longs, and that doesn't actually affect the array size. The tracking array size [for a given count cap] is determined by the highest trackable value (and the lowest discernable value, which for most people is just the default of 1). This is true both for fixed size and for auto-sizing histograms. Fixed size has the benefit of absolutely-zero-allocation. Auto-sizing may resize the array at times (that number is capped: you'd never need to resize more than 55 times. 55 would be to cover up to Long.MAX_VALUE. E.g. if you never see a value greater than 3.6T nanoseconds (an hour), then you will at most resize 34 times). When those infrequent resizings do happen, the single recording call that triggers them will see a significantly longer recording time (as it will be the one allocating a new array and moving some stuff around). The benefit is that auto-sizing will keep the array as small as needed to track the actual highest-actually-seen value. BTW, with a DoubleHistogram, the array size is kept to what is needed to the actual range of experienced values , from smallest experienced to largest experienced, as there is no lowest discernable value there. A DoubleHistogram will not only auto-size, it will also auto-range (with shifts that don't change size) to cover the actually experienced part of the 2^(+/- 2048) exponential range.

**Comment by giltene** [comment]
And to clarify about the PackedHistogram recording speed: It will be slower than the blazing fast Histogram (which does almost 400M recording per second on my nice 2018 Macbook Pro), by about an order of magnitude. PackedHistogram can still do about 40M+ recording per second on that machine. 

And about footprint: By "less storage than a ShotHistigram", I mean "probably 20x less storage for typical use cases..."

**Comment by luciferous** [comment]
Those are great numbers, I'll have to look into it a bit further.

I understand your comment, above this one, but I'm not sure what it's addressing of what I wrote. The ShortCountsHistogram will be less storage than Histogram because of the counts array, so I was looking to implement a ShortRecorder (what Recorder is to Histogram but for ShortCountsHistogram). Is this an incorrect line of thinking?

**Comment by luciferous** [comment]
Here's an outline: https://github.com/HdrHistogram/HdrHistogram/compare/master...luciferous:short-recorder?expand=1

**Comment by giltene** [comment]
>> I understand your comment, above this one, but I'm not sure what it's addressing of what I wrote.

I was responding to "I was looking to choose a backing array type dependent on the highest trackable value."  Perhaps you meant to say "...dependent on the highest trackable count"?

**Comment by luciferous** [comment]
I was referring to [highestTrackableValue](https://github.com/HdrHistogram/HdrHistogram/blob/master/src/main/java/org/HdrHistogram/AbstractHistogram.java#L39), unless I'm misinterpreting its meaning.

**Comment by luciferous** [comment]
Hi @giltene, any thoughts on my branch?

**Comment by giltene** [comment]
> I am referring to [highestTrackableValue](https://github.com/HdrHistogram/HdrHistogram/blob/master/src/main/java/org/HdrHistogram/AbstractHistogram.java#L39), unless I'm misinterpreting its meaning.

Then that's what I meant by my long explanation. The choice of long/int/short is orthogonal to the implications of highestTrackableValue. highestTrackableValue only interacts with the length of the array. The word size of the array only impacts the count range: how many time a given value (or anything equivalent to it) can be repeatedly recorded before the histogram overflows.

**Comment by giltene** [comment]
> Hi @giltene, any thoughts on my branch?

You didn't implement a ConcyrrentshortHistogra, so for consistency your ShortRecorder shouild really be a SingWriterShortRecorder.

My ceoncern is the code duplication involved (highlighted by the confisuion between single writer and general case above), and the ongoing maintenance later. I.e. any changes to atomic histograms, concurtrent histograms, or recorders (both single and multi-writer) will need to make identical modifications in three implementations. I moved to a subclassing structure under Histogram for Atomic/Synchronized/Concurrent to mimizine some changes. And I'm looking for a way to collapse the word size choices into common code as well.

A packed histogram (as a subclass of Histogram, with atomic and concurrent variants) would fit in nicely, and could be used by common recorders (or recorders that subclass the current ones). But it doesn't quite do the same thing and the short./int variants.

**Comment by giltene** [comment]
(oops, didn't mean to close. hit worng button)

**Comment by luciferous** [comment]
Yes, I'm also concern about the code duplication. The classes are otherwise exactly the same except for the replaced types. We could parameterize the types via generics, but I'm sure we don't want an array of boxed version of int, short and long. Maybe there is a way to do it while still maintaining the unboxed type for counts array.

I can spend some time to look into this if you think it would be acceptable to make the design more generic. But, if you are opposed to generics in the design, then I won't proceed. Please let me know.

**Comment by giltene** [comment]
I could envision various ways to extend Histogram in a backwards compatible way to indicate the inteded size of the counts words:
1. via generics. I.e. Histogram<T> with acceptable Histogram<Long>, Histogram<Integer>, Histogram<Short> [defautls to long when unspecified). This one "looks cool at first", but is wrong semantically IMO, as the reader's expectation would be that the type relates to the value, and not to the count.
2. via an additional (optional) constructor argument that would indicate the type, i.e. Long.TYPE/Integer.TYPE/Short.TYPE (with a default of Long.TYPE). This, along with 3 internal counts arrays (only one of which would be populated) and conditional code everywhere would work, and would be binary compatible with existing APIs. But it still "smells" a bit.

My core question comes down to what the motivation for these non-long count levels are. The main motivation comes from cases where there are many histograms in the heap, and a space savings of 2x or 4x per instance makes a significant difference. 

I propose that we abandon the short/int forms altogether, depreciating them over time, and replacing them with the seemingly-superior (for their use cases) PackedHistogram. The difference in speed between a Histogram and a PackedHistogram (and the loss of key qualities like "entirely zero-allocation" and "no resizing, ever" are important to low latency workloads) would not present a real problem for workloads with a huge number of histograms in the heap. And since a PackedHistogram will tend to save an additional order of magnitude in space over the short and int forms, it would tend to be the always-preferred case if the choice was available.

**Comment by giltene** [comment]
> Here's an outline of what I mean: [master...luciferous:short-recorder](https://github.com/HdrHistogram/HdrHistogram/compare/master...luciferous:short-recorder)

Looking a bit more into the code above, your ShortAtomicHistogram does not do what is needed. As written, it will have the exact same footprint as an AtomicHistogram (it uses an AtomicLongArray of the exact same length), so the ShortRecorder saves nothing compared to a Recorder. You would need to implement an AtomicShortArray (which the JDK does not have, tho it does have an AtomicIntegerArray) to get the 4x reduction in storage impact you are probably looking for.

**Comment by giltene** [comment]
> I propose that we abandon the short/int forms altogether, depreciating them over time,
> and replacing them with the seemingly-superior (for their use cases) PackedHistogram. 

Update on this: while a PackedHistogram seems to work well, I am now wrestling with how to implement Atomic and Concurrent variants. Lock-free insertion of counts for not-yet-included values into a packed array form is an "interesting" problem. One that I hope to solve ove rthe coming weeks, but not a one-weekend sort of thing.

**Comment by luciferous** [comment]
Hi @giltene - thanks for the replies. Let me know if I can help with the PackedHistogram. It makes sense to me that's the way forward. I'll close this issue, feel free to open it if there's more to discuss.

**Comment by giltene** [comment]
@luciferous https://github.com/HdrHistogram/HdrHistogram/releases/tag/HdrHistogram-2.1.12 includes PackedHistogram variants (PackedHistogram, PackedConcurrentHistogram, PackedDoubleHistogram, and PackedConcurrentDoubleHistogram), and the recorder variants now support construction with an (optional) packed indicator. This is the first version that includes these packed behaviors, so use with care, and please provide feedback.
