### ISSUE TITLE
Plotting Service feature legend not showing

### ISSUE THREAD

**Issue by NewBermuda** [HdrHistogram/HdrHistogram#167]
Hi there,

sorry to bother again about the plotting service.
But I just discovered when importing your own histogram data, the legend is not working probably. 
Could you try it with your own data to see if it's the same for you?
For me, the default example shows the legend, but as soon as I load my own data it disappears.
It was still working before I submitted my prior issue. 
The legend is built from the input file names, right?
![loss_15](https://user-images.githubusercontent.com/13998895/85778143-8ff21700-b722-11ea-93d9-2340a030a460.png)

**Comment by giltene** [comment]
Fixed with https://github.com/HdrHistogram/HdrHistogram/commit/5071aec2809d7d2f0564c1e81ce73c6d9e470731 and https://github.com/HdrHistogram/HdrHistogram/commit/33cb3bb3c25bb1aad45b5639ceec2768b9cc9275

**Comment by giltene** [comment]
Thanks for the catch. I changed the same in the gh-pages place that holds the actual online charter. Please check and verify it works for you too now.

**Comment by NewBermuda** [comment]
Thank you again, it works great now!
