### ISSUE TITLE
build errors in intellij

### ISSUE THREAD

**Issue by pdeva** [HdrHistogram/HdrHistogram#172]
seeing this error in intellij

```
Cannot resolve plugin org.apache.maven.plugins:maven-resources-plugin:<unknown>
Cannot resolve plugin org.apache.maven.plugins:maven-install-plugin:<unknown>
Cannot resolve plugin org.apache.maven.plugins:maven-deploy-plugin:<unknown>
```

**Comment by giltene** [comment]
Can you describe which version of IntelliJ and what JDKs you are seeing these errors with, and what the specific way you are invoking maven is?

I just tried a freshly cloned repo with IntelliJ 2020.2 (created with file->new->new project from version control with https://github.com/HdrHistogram/HdrHistogram.git as the URI). I tested it with a wide variety of JDK versions configured for the project (\the latest versions of Zulu 8, Zulu 11, Zulu 13, Zulu 14, Zuylu 15-ea), and for me, they all pass "maven test" when invoked from within IntelliJ (with Maven->HdrHistogram>Lifecycle->test).

**Comment by pdeva** [comment]
intellij 2020.2. jdk 11
![image](https://user-images.githubusercontent.com/3190176/92513251-d7862c00-f1c4-11ea-8e2d-acd8f5ad1db1.png)

**Comment by pdeva** [comment]
seems like an intellij issue:
https://youtrack.jetbrains.com/issue/IDEA-250370
