### ISSUE TITLE
Automatic-Module-Name attribute

### ISSUE THREAD

**Issue by lenborje** [HdrHistogram/HdrHistogram#181]
Could you please add an `Automatic-Module-Name` attribute to the manifest? While not strictly necessary for deployment in a modular context, it would remove some warnings in my build.

If it were specified as `Automatic-Module-Name: HdrHistogram` (i.e., equal to the otherwise automatically implied module name) I believe all warnings would be gone without any further impact.

Cf. [Oracle's doc on JAR Main Attributes](https://docs.oracle.com/en/java/javase/11/docs/specs/jar/jar.html#main-attributes)

**Comment by A248** [comment]
I would argue that an Automatic-Module-Name is **effectively necessary** for stable usage in a modular application. It is not a missing feature, but a bug, for a library to be missing one.

http://branchandbound.net/blog/java/2017/12/automatic-module-name/ provides a good guide on how to achieve this

**Comment by giltene** [comment]
Thanks for flagging this and for the PR.
