### ISSUE TITLE
Link to "Plot histogram file(s)" is broken on http://www.hdrhistogram.org/ 

### ISSUE THREAD

**Issue by karlmdavis** [HdrHistogram/HdrHistogram#183]
Specifically, this link: <https://hdrhistogram.github.com/HdrHistogram/plotFiles.html>.

Looks like it was caught by GitHub deprecating `foo.github.com` subdomains, as it returns a cheery 404 about that.

**Comment by giltene** [comment]
Fixed with https://github.com/HdrHistogram/HdrHistogram/commit/ae14ee37c41311010ccd5211ca7de52e55e8bdd9
