### ISSUE TITLE
ArrayIndexOutOfBounds in DoubleHistogram.recordValue

### ISSUE THREAD

**Issue by vnickolov** [HdrHistogram/HdrHistogram#190]
Hello there, 

I am having some issues when recording values, here is a small test that can reproduce the problem using `HdrHistogram 2.1.12`:

```
import org.HdrHistogram.DoubleHistogram;
import org.junit.jupiter.api.Test;

import static org.assertj.core.api.Assertions.assertThatNoException;


class DoubleHistogramTest {

    @Test
    void recordValue() {
        var values = new double[]{
            0.1473766911865831,
            0.06643103322406599,
            1.45519152283669E-11,
            1.45984899931293E-77
        };

        var histogram = new DoubleHistogram( 5);
        histogram.setAutoResize(true);
        for (double value : values) {
            assertThatNoException().isThrownBy(() -> histogram.recordValue(value));
        }
    }

}
```

With this I am getting the following result:
```
Expecting code not to raise a throwable but caught
  "java.lang.ArrayIndexOutOfBoundsException: The value 1.45984899931293E-77 is out of bounds for histogram, current covered range [1.4551915228366852E-11, 0.25) cannot be extended any further.
Caused by: java.lang.ArrayIndexOutOfBoundsException: Cannot resize histogram covered range beyond (1L << 63) / (1L << 17) - 1.
Caused by: java.lang.ArrayIndexOutOfBoundsException: Operation would overflow, would discard recorded value counts
	at org.HdrHistogram.DoubleHistogram.autoAdjustRangeForValueSlowPath(DoubleHistogram.java:445)
	at org.HdrHistogram.DoubleHistogram.autoAdjustRangeForValue(DoubleHistogram.java:411)
	at org.HdrHistogram.DoubleHistogram.recordSingleValue(DoubleHistogram.java:364)
	at org.HdrHistogram.DoubleHistogram.recordValue(DoubleHistogram.java:289)
	at org.neo4j.gds.result.DoubleHistogramTest.lambda$recordValue$0(DoubleHistogramTest.java:42)
```

I've been digging through the code and found https://github.com/HdrHistogram/HdrHistogram/blob/7b0edce258c0847387e3ed532057556b1cc6bd9d/src/main/java/org/HdrHistogram/DoubleHistogram.java#L408

I am going on a hunch here but I think the comparison should take into an account the `numberOfSignificantValueDigits` of the passed value.

**Comment by giltene** [comment]
@vnickolov . The precision of the histogram (numberOfSignificantValueDigits) cannot be used to ignore the exponential range in double values when recording into a DoubleHistogram, or to "round" the exponents in values based on the specified histogram precision. The values you are attempting to record into a single DoubleHistogram span 76 decimal orders of magnitude (they include both 0.1473766911865831 and 1.45984899931293E-77), and as the error message explains, DoubleHistograms are limited in dynamic range, such that the ratio between the smallest non-zero value recorded in the histogram, and the largest value recorded in the histogram cannot be larger than [(1L << 63) / (1L << 17) - 1] [this is for a histogram with a precision 5 decimal points, as specified in your example. For lower precision the covered range would be somewhat larger, of e.g. 2 decimal points, it would be (1L << 63) / (1L << 7) - 1 ].

If you are looking for value-rounding behavior that would e.g. interpret small non-zero numbers as zero, you can use HdrHistogram to record integer values, and round as you wish when you record them.

**Comment by vnickolov** [comment]
Thank you for the detailed explanation and the suggestion @giltene! I am closing this since there is nothing to be done at this end, we are going to look at your suggestion. 

Thanks once again!
