### ISSUE TITLE
Maven Surefire cannot read module from 2.2.1 HdrHistogram Jar

### ISSUE THREAD

**Issue by karianna** [HdrHistogram/HdrHistogram#206]
I may have discovered a downstream challenge. The Maven Surefire plugin does not seem to be able to read the module using Maven 3.9.7, Java 11.0.23 and latest plugins:

[DEBUG] Forking command line: /bin/sh -c cd '/Users/martijnverburg/workspace/microsoft/Censum/censum-ui/censum-desktop' && '/Library/Java/JavaVirtualMachines/temurin-11.jdk/Contents/Home/bin/java' '@/Users/martijnverburg/workspace/microsoft/Censum/censum-ui/censum-desktop/target/surefire/surefireargs-20240529185813763_18' '/Users/martijnverburg/workspace/microsoft/Censum/censum-ui/censum-desktop/target/surefire' '2024-05-29T18-58-08_261-jvmRun1' 'surefire-20240529185813763_16tmp' 'surefire_5-20240529185813763_17tmp'
[DEBUG] Fork Channel [1] connected to the client.
[ERROR] Error occurred during initialization of boot layer
**[ERROR] java.lang.module.FindException: Error reading module: /Users/martijnverburg/.m2/repository/org/hdrhistogram/HdrHistogram/2.2.1/HdrHistogram-2.2.1.jar
[DEBUG] Caused by: java.lang.module.InvalidModuleDescriptorException: Package org.HdrHistogram$packedarray not found in module**
[DEBUG] Closing the fork 1 after not saying Good Bye.

I can confirm that `/Users/martijnverburg/.m2/repository/org/hdrhistogram/HdrHistogram/2.2.1/HdrHistogram-2.2.1.jar` is there and that it contains a file: `META-INF/versions/9/module-info.class`.

_Originally posted by @karianna in https://github.com/HdrHistogram/HdrHistogram/issues/205#issuecomment-2136682652_

**Comment by karianna** [comment]
A fix has been proposed to ModiTect https://github.com/moditect/moditect/pull/250

**Comment by giltene** [comment]
@karianna was HdrHistogram 2.1.12 working ok where 2.2.1 is breaking as per above? If so, reverting the change to use moditect until moditect deals with these package names correctly would work, going back to just using Automatic-Module-Name. If not, I'll likely need to implement a multi-version jar and a hand-crafted module-info.java ...

**Comment by karianna** [comment]
Yes previous version worked fine, thanks!

**Comment by giltene** [comment]
Ok. Just pushed out HdrHistogram 2.2.2 with change from using moditect to just using Automatic-Module-Name. Can you check to see if this resolves the above? 
Addressed with https://github.com/HdrHistogram/HdrHistogram/commit/c655bfa1654158157605cf30987c4e5e5d8c7b2b

**Comment by karianna** [comment]
That fixed it for me, thanks!
