### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by btorpey** [HdrHistogram/HdrHistogram#50]
Getting a compile error on master, w/eclipse and also from cmd line -- any suggestions?

TIA!

btmacpro:HdrHistogram btorpey$ ant
Buildfile: /Users/btorpey/miscinfo/blog/code/HdrHistogram/build.xml

init:

clean.module.hdrhistogram:
   [delete] Deleting directory /Users/btorpey/miscinfo/blog/code/HdrHistogram/out/production/HdrHistogram

clean:

compile.module.hdrhistogram.production:
    [mkdir] Created dir: /Users/btorpey/miscinfo/blog/code/HdrHistogram/out/production/HdrHistogram
    [javac] /Users/btorpey/miscinfo/blog/code/HdrHistogram/build.xml:133: warning: 'includeantruntime' was not set, defaulting to build.sysclasspath=last; set to false for repeatable builds
    [javac] Compiling 34 source files to /Users/btorpey/miscinfo/blog/code/HdrHistogram/out/production/HdrHistogram
    [javac] /Users/btorpey/miscinfo/blog/code/HdrHistogram/src/main/java/org/HdrHistogram/HistogramLogProcessor.java:50: error: cannot find symbol
    [javac]     public static final String versionString = "Histogram Log Processor version " + Version.version;
    [javac]                                                                                     ^
    [javac]   symbol:   variable Version
    [javac]   location: class HistogramLogProcessor
    [javac] 1 error

BUILD FAILED
/Users/btorpey/miscinfo/blog/code/HdrHistogram/build.xml:133: Compile failed; see the compiler error output for details.

Total time: 1 second

**Comment by giltene** [comment]
We generally use maven to build HdrHistogram ("mvn clean package", artifacts appear in the target directory). The Version.version file is auto-generated by maven with the appropriate version from the pom.xml file, and the ant script does auto-generate it. 

ant [seems to] build fine after a maven build, if you need to use it for some reason. But it is mostly unused.

**Comment by btorpey** [comment]
Duh!  I guess you can tell I'm not a Java guy ;-)  I saw a build.xml and figured that meant ant.

Thanks!
