### ISSUE TITLE
gnuplot histogram question

### ISSUE THREAD

**Issue by btorpey** [HdrHistogram/HdrHistogram#51]
I'd love to be able to plot a histogram of latencies against SLA, similar to what you use in your presentations, and preferably using gnuplot.

However, maybe I'm dense, but I can't make sense of the format of the SLA data in the gnuplot example.  How would I define my own SLA values?  Any pointers would be much appreciated!

**Comment by giltene** [comment]
To help explain this, I just updated the Excel sheet example with a detailed example of an SLA statement and a derived SLA steps for charting. See it here: https://github.com/HdrHistogram/HdrHistogram/blob/master/PercentileChartExample.xlsx

you can use that logic example in generating your own SLA step values for e.g. gunplot.

There are three key thing to understand about plotting SLA lines:

1. The X axis is logarithmic, and represents 1/(1-Quantile) [Quantile being Percentile/100, i.e. a fraction in the 0...1 range]. I.e. 0% is X=1, 90% is X=10, 99% is X=100, etc.

2. SLAs are charted as step functions, so each X axis point needs two values: the one to it's left (the level acceptable at this percentile) and the one to it's right (the level acceptable at the next percentile point in the SLA).

3. 100% translates to infinity on the X axis. So depending on the charting tool and the auto-sizing behavior of your X axis, you may want to replace 100% with "the highest percentile on the X axis".

**Comment by btorpey** [comment]
Thanks Gil!   

Great stuff.
