### ISSUE TITLE
Serialized SynchronizedHistogram looses auto resize true property

### ISSUE THREAD

**Issue by dahankzter** [HdrHistogram/HdrHistogram#52]
We noticed it by chance the other day. Our histograms are stored in a cache that rolls over to disk and we thought is safe since they should be serializable.

**Comment by giltene** [comment]
Fixed with https://github.com/HdrHistogram/HdrHistogram/commit/05ef3d71061696e4612f146aa24a140ea0653e2f which also carries start/end timestamps info into serialized format. 

Note that the new serialized form does not support reading of serialized histograms of older/prior versions.

**Comment by dahankzter** [comment]
Thank! Any plans for a maven release soon? We can build ourselves but it is neat not to have to.
