### ISSUE TITLE
Histogram subtract() method broken for ShortCountsHistogram

### ISSUE THREAD

**Issue by mikkokar** [HdrHistogram/HdrHistogram#64]
An attempt to subtract a ShortCountsHistogram from another results an exception to be thrown with stack trace:

    java.lang.IllegalArgumentException: would overflow short integer count
    	at org.HdrHistogram.ShortCountsHistogram.addToCountAtIndex(ShortCountsHistogram.java:54)
    	at org.HdrHistogram.AbstractHistogram.subtract(AbstractHistogram.java:637)
    	at 
        ...

This is obvious from code though. On line 637 of AbstractHistogram.java the subtract() method negates the other histogram's sample count before calling addToCountAtIndex():

    addToCountAtIndex(i, -otherCount);

But addToCountAtIndex throws an exception because the value is negative:

    @Override
    void addToCountAtIndex(final int index, final long value) {
        int normalizedIndex = normalizeIndex(index, normalizingIndexOffset, countsArrayLength);
        short currentCount = counts[normalizedIndex];

        // THE BUG IS HERE, SEE BELOW:
        if ((value < 0) || (value > Short.MAX_VALUE)) {
            throw new IllegalArgumentException("would overflow short integer count");
        }

        ...

**Comment by giltene** [comment]
Addressed with https://github.com/HdrHistogram/HdrHistogram/commit/f09184fd6faeacc817d32b96f32835abc19e6791. Did not make it into 2.1.5, but will into next release.
