### ISSUE TITLE
Java HDR histogram getMinValue() returns Long.MAX_VALUE on empty histogram.

### ISSUE THREAD

**Issue by mikkokar** [HdrHistogram/HdrHistogram#65]
In a Java version of HDR histogram, a call to getMinValue() on an empty histogram, i.e. one with no recorded values, yields Long.MAX_VALUE. Is this the intended behaviour, or should the getMinValue() return zero?

This is using version 2.1.4 from Maven Central.

Following test fails:

    @Test
    public void emptyHistogramReturnsZeroAsMinumumValue() {
        Histogram histogram = new org.HdrHistogram.Histogram(2);

        assertThat(histogram.getTotalCount(), is(0L));
        assertThat(histogram.getMinValue(), is(0L));
    }

Output:

    java.lang.AssertionError: 
    Expected: is <0L>
     but: was <9223372036854775807L>

**Comment by giltene** [comment]
0 would be "just as wrong" as Long.MAX_VALUE (or Long.MAX_VALUE is "just as right" as 0).

The min and max values of a histogram that has no recorded values is undefined. I'll clarify this in the JavaDoc for both getMinValue and getMaxValue in coming updates.
