### ISSUE TITLE
HistogramLogProcessor does not close resources

### ISSUE THREAD

**Issue by ennerf** [HdrHistogram/HdrHistogram#66]
[HistogramLogProcessor.main()](https://github.com/HdrHistogram/HdrHistogram/blob/master/src/main/java/org/HdrHistogram/HistogramLogProcessor.java) does not close the opened FileStreams. Trying to use it inside another application results in files that can't be deleted.

**Comment by giltene** [comment]
Addressed with https://github.com/HdrHistogram/HdrHistogram/commit/02da86c60893f1c54dc44db7c95f6f47fffbf57b and included in 2.1.5
