### ISSUE TITLE
LogWriter/Reader have mixed notions of start vs. base time

### ISSUE THREAD

**Issue by nitsanw** [HdrHistogram/HdrHistogram#69]
In HistogramLogWriter we can optionally set a baseTime which will lead to following histograms logged being attributed to a relative timestamp. This base time is set independently from the recommended logging of start time.
On the reader side it is assumed that start time IS base time (see https://github.com/HdrHistogram/HdrHistogram/blob/e11b66f30c6775893ca5b24ca854f0b55cdbc6d1/src/main/java/org/HdrHistogram/HistogramLogReader.java#L191):
    
                if (scanner.hasNext("\\#.*")) {
                    // comment line
                    if (scanner.hasNext("#\\[StartTime:")) {
                        scanner.next("#\\[StartTime:");
                        if (scanner.hasNextDouble()) {
                            startTimeSec = scanner.nextDouble(); // start time represented as seconds since epoch
                        }
                    }
                    scanner.nextLine();
                    continue;
                }

                if (scanner.hasNext("\"StartTimestamp\".*")) {
                    // Legend line
                    scanner.nextLine();
                    continue;
                }

                // Decode: startTimestamp, intervalLength, maxTime, histogramPayload

                final double offsetStartTimeStampSec = scanner.nextDouble(); // Timestamp start is expect to be in seconds
                final double absoluteStartTimeStampSec = getStartTimeSec() + offsetStartTimeStampSec;

                final double intervalLengthSec = scanner.nextDouble(); // Timestamp length is expect to be in seconds
                final double offsetEndTimeStampSec = offsetStartTimeStampSec + intervalLengthSec;
                final double absoluteEndTimeStampSec = getStartTimeSec() + offsetEndTimeStampSec;

                final double startTimeStampToCheckRangeOn = absolute ? absoluteStartTimeStampSec : offsetStartTimeStampSec;

                if (startTimeStampToCheckRangeOn < rangeStartTimeSec) {
                    scanner.nextLine();
                    continue;
                }

                if (startTimeStampToCheckRangeOn > rangeEndTimeSec) {
                    return null;
                }

Start time and base time can be set multiple times in the process of reading/writing a log.
I can see the value of reporting relative timestamps, I can also see the value of reporting the log or application start time. The current state leads to confusing scenarios where an application which writes the start time (as recommended by the docs) and goes on to log histograms with the timestamps set will end up with a log that is written with absolute timestamps but read with relative timestamps.
To prevent confusion and displeasure I suggest we set the baseTime when logging start time, and log the start time when setting base time. This will at least reduce confusion. Alternatively we could use a different mechanism to determine base time (i.e a different prefix for the reader to detect) and use it to communicate the base time setting.
Finally, in the absence of a base time the reader should still be able to filter relative ranges in the log, and HistogramLogProcessor should expose that option (currently the default but broken for logs containing the start time).

**Comment by giltene** [comment]
Addressed (I hope) with https://github.com/HdrHistogram/HdrHistogram/commit/019689cbf27f008478bbf4bcfbb7cbfb8fdba592 and https://github.com/HdrHistogram/HdrHistogram/commit/d27b4192a98e5f7692a42fc250daa3bec5067dcf

Log files now support:
- StartTime being optional (derived from 1st line if missing)
- A new optional explicit BaseTime
- BaseTime is derived (if not specified explicitly) from 1st line's relationship to start time.

Together, these changes make relative time range filtering on files written with either relative or explicit timestamps (base time set to 0 or to start time) regardless of What start time is set to.

**Comment by nitsanw** [comment]
Hmmm... it's a good start.
The problem I see now is that StartTime is just after first observed TS. This is a real log from YCSB:
#[StartTime: __1438613579.295__ (seconds since epoch), Mon Aug 03 07:52:59 PDT 2015]
"StartTimestamp","Interval_Length","Interval_Max","Interval_Compressed_Histogram"
__1438613579.290__,0.660,0.488,...
This is happening because of initialisation order in the OneMeasurementHdrHistogram class where the Recorder is created before the log file is set up and so the first interval starts at the time of it's creation.

**Comment by giltene** [comment]
With https://github.com/HdrHistogram/HdrHistogram/commit/624ebd2274a489b30e02277f962d5c71e3ecf1f0 I added a 1 year grace period for the comparison with StartTime used in determining absolute or relative timestamp interpretation. This will allow "reasonable" start-time reordering races (between StartTime logging and first recording histogram interval start) to exist with no parsing problem.
