### ISSUE TITLE
cmd line util to parse csv file?

### ISSUE THREAD

**Issue by btorpey** [HdrHistogram/HdrHistogram#74]
I'm looking for a way to feed data parsed from an existing log file to HdrHistogram.  At first, I thought that HistogramLogProcessor would do the trick, but now I'm not so sure.

Is there something like that ? 

Thanks!

**Comment by giltene** [comment]
Take a look at jHiccup (https://github.com/giltene/jHiccup), and specifically at the -f and -fz options. Is that sort of what you are talking about?

**Comment by btorpey** [comment]
Hi Gil:

I dont think so.  I have existing files with latencies that I want to feed (off-line) to HdrHistogram.   I massage the input logs to create something that looks like:

timestamp,latency

I wrote a little CSV2HdrHistogram class to feed that data to HdrHistogram, but it occurred to me that I should not re-invent that particular wheel, if possible.

If something like that doesn’t already exist, I’d be happy to contribute what I have.

Regards,

Bill

**Comment by btorpey** [comment]
Hi Gil:

On even closer inspection, not sure that jHiccup will work for what I need — if I read the docs correctly, it assumes that samples occur at regular intervals, and that is not the case.  (These are “real” measured latencies of messages that occur at indeterminate intervals).

In fact, the timestamp column is not really relevant — the only thing I care about is getting a distribution of latencies as percentiles, which I can then plot using gnuplot.

Thanks.

Bill

**Comment by giltene** [comment]
jHiccup is mainly focused on measuring hiccups, but it's -f mode simply reports on the input it is provided (with correction for CO being optional).

% java -jar jHiccup.jar -f inputfile -r 100000000 
(the large -r value makes sure no corrections are done).

Should provide you with a histogram log file that represents the latency distribution (as a whole and per 5 second time interval) in the input file. You can then use HistogramLogProcessor to consume that log file.
