### ISSUE TITLE
Incorrect output from getValueAtPercentile(long precentile) of Histogram class

### ISSUE THREAD

**Issue by jai1** [HdrHistogram/HdrHistogram#95]
```
import org.HdrHistogram.*;

public class Main {

public static void main(String[] args) throws InterruptedException {
    Histogram histogram = new Histogram(5);
    histogram.recordValue(1000000);
    histogram.recordValue(1000001);
    histogram.recordValue(1000002);
    histogram.recordValue(90);
    histogram.recordValue(10);

    System.err.println(histogram.getValueAtPercentile(50.0));
}
}
```

In this case I am expecting the output to be 1000000, but actual output is 1000003

My maven settings are:-

    <dependency>
        <groupId>org.hdrhistogram</groupId>
        <artifactId>HdrHistogram</artifactId>
        <version>2.1.8</version>
    </dependency>

**Comment by giltene** [comment]
This is correct behavior. With 5 decimal points of specified resolution/separation (in your example), any result that is 1000000 +/- 100 would be correct. 1000003 is well within that range, and histogram.valuesAreEquivalent(1000000, 1000003) would/should return true.
Note that you can use histogram.lowestEquivalentValue(1000000) and
histogram. highestEquivalentValue(1000000) to establish the range of equivalent values.

**Comment by jai1** [comment]
@giltene Thanks for the clarification.
