### ISSUE TITLE
HistogramLogReader::nextIntervalHistogram should throw exception when hitting malformed line in log

### ISSUE THREAD

**Issue by nitsanw** [HdrHistogram/HdrHistogram#99]
Consider the current case where the reader returns a null, which is indicative of error or EOF with no way to discriminate.

**Comment by mikeb01** [comment]
Should the iterator be allowed to continue onto the next line and keep parsing?

**Comment by nitsanw** [comment]
I think it should move it's position to the start of next line before throwing the exception, so that iteration can resume from next line.
The errors I've seen are malformed lines, issues with unintended parallel logging etc. So there will be one line that is bad in a log that is otherwise full of goodness.

**Comment by nitsanw** [comment]
more thought on this? I realize this is an API breaking change, but it's needed

**Comment by nitsanw** [comment]
Perhaps an easy option is to add a "hasNext" method rather than throwing a checked exception. This would leave existing code as working/broken as before and let new code use the new method to discover if it needs to keep going.

**Comment by nitsanw** [comment]
See fix in branch:
https://github.com/nitsanw/HdrHistogram/tree/logreader-hasnext
If this looks good I'll use the new feature in log processor and make a PR.
I've tested with my HDR log processing utils and this helps resolve my issue.

**Comment by nitsanw** [comment]
ping?

**Comment by giltene** [comment]
Addressed with https://github.com/HdrHistogram/HdrHistogram/commit/4399d30dd73d7a38e37890812a7c63f2fa0588f2
